import { FormType } from '@core/formly/models/form-field-item';
import { LucideIconType, TreeMenuType } from '@shared/types/ui.types';

export const FORM_ELEMENTS_ICONS: Record<FormType, LucideIconType> = {
  [FormType.Alert]: 'lucideInfo',
  [FormType.Checkbox]: 'lucideSquareCheck',
  [FormType.Divider]: 'lucideMinus',
  [FormType.Email]: 'lucideMail',
  [FormType.Field]: 'lucideSquare',
  [FormType.Group]: 'lucideSquare',
  [FormType.Multicheckbox]: 'lucideSquareCheck',
  [FormType.Multiselect]: 'lucideChevronsUpDown',
  [FormType.Number]: 'lucideHash',
  [FormType.Paragraph]: 'lucideFileText',
  [FormType.Radio]: 'lucideCircleDot',
  [FormType.Rating]: 'lucideStar',
  [FormType.Select]: 'lucideChevronsUpDown',
  [FormType.Text]: 'lucideType',
  [FormType.Textarea]: 'lucideAlignLeft',
  [FormType.Title]: 'lucideHeading1',
};

export const FORM_ELEMENT_CATEGORIES: TreeMenuType<FormType>[] = [
  {
    id: 'layout',
    label: 'Layout',
    items: [
      {
        id: 'layout-container',
        label: 'Container',
        icon: FORM_ELEMENTS_ICONS[FormType.Group],
        value: FormType.Group,
        description: 'Groups fields together.',
      },
      {
        id: 'layout-divider',
        label: 'Divider',
        icon: FORM_ELEMENTS_ICONS[FormType.Divider],
        value: FormType.Divider,
        description: 'Adds a horizontal separator.',
      },
      {
        id: 'layout-label',
        label: 'Title',
        icon: FORM_ELEMENTS_ICONS[FormType.Title],
        value: FormType.Title,
        description: 'Displays a section heading.',
      },
      {
        id: 'layout-paragraph',
        label: 'Paragraph',
        icon: FORM_ELEMENTS_ICONS[FormType.Paragraph],
        value: FormType.Paragraph,
        description: 'Adds descriptive text.',
      },
      {
        id: 'layout-message',
        label: 'Message',
        icon: FORM_ELEMENTS_ICONS[FormType.Alert],
        value: FormType.Alert,
        description: 'Shows an informational alert.',
      },
    ],
  },
  {
    id: 'fields',
    label: 'Fields',
    items: [
      {
        id: 'fields-text',
        label: 'Text',
        icon: FORM_ELEMENTS_ICONS[FormType.Text],
        value: FormType.Text,
        description: 'Single-line text input.',
      },
      {
        id: 'fields-textarea',
        label: 'Textarea',
        icon: FORM_ELEMENTS_ICONS[FormType.Textarea],
        value: FormType.Textarea,
        description: 'Multi-line text input.',
      },
      {
        id: 'fields-number',
        label: 'Number',
        icon: FORM_ELEMENTS_ICONS[FormType.Number],
        value: FormType.Number,
        description: 'Numeric input data.',
      },
      {
        id: 'fields-email',
        label: 'Email',
        icon: FORM_ELEMENTS_ICONS[FormType.Email],
        value: FormType.Email,
        description: 'Email address input.',
      },
      {
        id: 'fields-select',
        label: 'Select',
        icon: FORM_ELEMENTS_ICONS[FormType.Select],
        value: FormType.Select,
        description: 'Dropdown selection.',
      },
      {
        id: 'fields-multiselect',
        label: 'Multiselect',
        icon: FORM_ELEMENTS_ICONS[FormType.Multiselect],
        value: FormType.Multiselect,
        description: 'Multiple options selection.',
      },
      {
        id: 'fields-checkbox',
        label: 'Checkbox',
        icon: FORM_ELEMENTS_ICONS[FormType.Checkbox],
        value: FormType.Checkbox,
        description: 'Single checkbox option.',
      },
      {
        id: 'fields-checkbox-group',
        label: 'Checkbox group',
        icon: FORM_ELEMENTS_ICONS[FormType.Multicheckbox],
        value: FormType.Multicheckbox,
        description: 'Multiple checkboxes.',
      },
      {
        id: 'fields-radio',
        label: 'Radio',
        icon: FORM_ELEMENTS_ICONS[FormType.Radio],
        value: FormType.Radio,
        description: 'Single-choice radio buttons.',
      },
      {
        id: 'fields-rating',
        label: 'Rating',
        icon: FORM_ELEMENTS_ICONS[FormType.Rating],
        value: FormType.Rating,
        description: 'Star rating input.',
      },
    ],
  },
  {
    id: 'advanced-fields',
    label: 'Advanced Fields',
    items: [],
  },
] as const;
